apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm-appsets
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: acm-appsets-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: acm-appsets-{{name}}
    spec:
      destination:
        namespace: bgdk
        server: "{{server}}"
      project: default
      source:
        path: apps/bgd/overlays/bgdk
        repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-apps/
        targetRevision: single-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-appsets-placement
  namespace: openshift-gitops
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
